FROM appgardner/gocv:v4.6.0-static as build
WORKDIR /go/src/dlc

WORKDIR /go/src/wegyb
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -tags static # -ldflags="-extldflags=-static"

FROM scratch
COPY --from=build /go/src/wegyb/wegyb /wegyb

ENTRYPOINT ["/wegyb"]
